### ISSUE TITLE
Create a Low-level Routine Library

### ISSUE THREAD

**Issue by DanielSacro** [G13-capstone/CLM-LLR-Firmware#6]
## Description
Implement a Low-level Routine Library that contains the functions for all low-level routines we intend to support. Functions should implement the functionality of each routine.

# Required Features
- [x] Driver for LCD Screen
- [x] Driver for USB Keyboard
- [x] ~~Driver for USB Mass Storage Device~~ --> Scrapped
- [x] Driver for Type-C connected Terminal
- [x] ~~Floating-point Operations~~
- [x] Data type conversions (partially complete)

**Comment by nic3-14159** [comment]
Minimal walking skeleton: low level routine for Type-C connected terminal
